### ISSUE TITLE
Include textdomain in strings

### ISSUE THREAD

**Issue by emdashcodes** [mikeyarce/subscriptions-checkout-for-woocommerce#1]
Each string wrapped in translation functions also needs a textdomain included. The textdomain is defined in the main plugin file, and is usually just the slug/name of the plugin.

So

`__( 'My Field' )`

should become

`__( 'My Field', 'subscriptions-checkout-for-woocommerce' )`

**Comment by mikeyarce** [comment]
Thanks Justin!  Closed in https://github.com/mikeyarce/subscriptions-checkout-for-woocommerce/commit/4881ab545c30732935a585e9fc558bca9ae3e7c9 .
